### ISSUE TITLE
Any wish to make a 200% scaled version?

### ISSUE THREAD

**Issue by wdhwg001** [outsetini/Air-for-Steam#104]
Well it's steam's fault. In windows, steam is blurry under 200% DPI. I've kept reporting this for a long time, but it seems this won't be fixed in a period of time.
So, the only way to make steam DPI-aware is to make a 200% scaled skin, enable it, and disable steam.exe's DPI scaling.
I really like this skin, so could you save our retina displays? Thanks.

Ps: The browser can be scaled by using css3 transform like this:
```css
body {
-webkit-transform: scale3d(2.0, 2.0, 1);
transform: scale3d(2.0, 2.0, 1);
transform-origin: 50% 0%;
-webkit-transform-origin: 50% 0%;
}
```
It's buggy, but currently I don't have a better idea since `zoom: 2` doesn't work.
